apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: hellorl
  name: hellorl
spec:
  replicas: 3
  selector:
    matchLabels:
      run: hellorl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hellorl
    spec:
      containers:
      - image: muhammadali448/nodejsappkuber
        name: container-1
        ports:
        - name: nodejs-port
          containerPort: 3000
        resources: {}
        livenessProbe:
          httpGet:
            path: /
            port: nodejs-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: nodejs-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
status: {}
