apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: secretdeploy
  name: secretdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      run: secretdeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: secretdeploy
    spec:
      volumes:
      - name: my-secretin-volume
        secret:
          secretName: user-login-s
      containers:
      - image: muhammadali448/nodejsappkuber
        name: secretdeploy
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - name: my-secretin-volume
          mountPath: /etc/credentials
          readOnly: true
        
status: {}
