apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: helloworld-dp1
  name: helloworld-dp1
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: helloworld-dp1
  type: NodePort
status:
  loadBalancer: {}
