apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod
  name: nginx-pod
spec:
  ports:
  - name: port-1
    port: 80
    protocol: TCP
  selector:
    run: nginx-pod
  type: NodePort
status:
  loadBalancer: {}
