apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod
  name: nginx-pod
spec:
  volumes:
  - name: config-volume
    configMap:
      name: nginx-config
      items:
      - key: reverseproxy.conf
        path: reverseproxy.conf      
  containers:
  - image: nginx
    name: nginx-container
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx/conf.d   
  - image: muhammadali448/nodejsappkuber
    name: nodejs-container
    ports:
    - containerPort: 3000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
