apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: helloworld-db
  name: helloworld-db-service
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    run: helloworld-db
  type: NodePort
status:
  loadBalancer: {}
