apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: helloworld
  name: hello-world-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: helloworld
  type: NodePort
status:
  loadBalancer: {}
